version: "3"                                                # docker-compose 버전이다
services:                                                   
    nginx:                                                  # 서비스명
      image: nginx:latest
      container_name: ng01                                # 컨테이너명
      ports:                                              # 포트 개방 "hostPort:dockerPort"으로 포워딩한다
        - "8000:8000"                                       
      volumes:                                            # 볼륨 마운트. 호스트의 파일을 사용하려면 필요하다
        - .:/code                                # 소스코드 마운트
        - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf # nginx 세팅 마운트
      depends_on:                                         # 'web'컨테이너가 구동되어야만 실행된다
        - web                                           

    web:                                                    
      build:
        context: .
        dockerfile: Dockerfile
      container_name: dg01                                
      command: "gunicorn project.wsgi:application -b 0:80"      # Django의 일반적인 runserver가 아닌 gunicorn을 사용해서 서버를 구동한다. 포트는 0.0.0.0:80으로 바인딩한다. 모든 아이피에서의 접속을 허용하고 80번 포트를 연다는 의미                                       
      volumes:                                            
        - .:/code                                
